# Generated by Django 2.1.15 on 2022-03-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20220313_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='no_one',
        ),
        migrations.RemoveField(
            model_name='user',
            name='no_two',
        ),
    ]
