# Generated by Django 2.1.15 on 2022-03-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20220313_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
