# Generated by Django 2.1.15 on 2022-03-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20220313_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='no_one',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='no_two',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='user',
            name='no_one',
            field=models.CharField(blank=True, max_length=280, verbose_name='no_one'),
        ),
        migrations.AlterField(
            model_name='user',
            name='no_two',
            field=models.CharField(blank=True, max_length=280, verbose_name='no_two'),
        ),
    ]
