# Generated by Django 2.1.15 on 2022-03-23 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20220321_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpostmodel',
            name='create_user',
        ),
        migrations.AddField(
            model_name='userpostmodel',
            name='user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
